// Generated by https://quicktype.io

export interface SynthFM {
    "@firmwareVersion":            string;
    "@earliestCompatibleFirmware": string;
    "@polyphonic":                 string;
    "@voicePriority":              string;
    "@mode":                       string;
    "@lpfMode":                    string;
    "@modFXType":                  string;
    osc1:                          Modulator1;
    osc2:                          Modulator1;
    lfo1:                          Lfo1;
    lfo2:                          any[];
    modulator1:                    Modulator1;
    modulator2:                    Modulator1;
    unison:                        Unison;
    compressor:                    Compressor;
    delay:                         Delay;
    defaultParams:                 DefaultParams;
    arpeggiator:                   Arpeggiator;
    modKnobs:                      ModKnob[];
}

export interface Arpeggiator {
    "@mode":       string;
    "@numOctaves": string;
    "@syncLevel":  string;
}

export interface Compressor {
    "@syncLevel": string;
    "@attack":    string;
    "@release":   string;
}

export interface DefaultParams {
    "@arpeggiatorGate":     string;
    "@portamento":          string;
    "@compressorShape":     string;
    "@oscAVolume":          string;
    "@oscAPulseWidth":      string;
    "@oscBVolume":          string;
    "@oscBPulseWidth":      string;
    "@noiseVolume":         string;
    "@volume":              string;
    "@pan":                 string;
    "@lpfFrequency":        string;
    "@lpfResonance":        string;
    "@hpfFrequency":        string;
    "@hpfResonance":        string;
    "@lfo1Rate":            string;
    "@lfo2Rate":            string;
    "@modulator1Amount":    string;
    "@modulator1Feedback":  string;
    "@modulator2Amount":    string;
    "@modulator2Feedback":  string;
    "@carrier1Feedback":    string;
    "@carrier2Feedback":    string;
    "@modFXRate":           string;
    "@modFXDepth":          string;
    "@delayRate":           string;
    "@delayFeedback":       string;
    "@reverbAmount":        string;
    "@arpeggiatorRate":     string;
    "@stutterRate":         string;
    "@sampleRateReduction": string;
    "@bitCrush":            string;
    "@modFXOffset":         string;
    "@modFXFeedback":       string;
    envelope1:              Envelope;
    envelope2:              Envelope;
    patchCables:            PatchCable[];
    equalizer:              Equalizer;
}

export interface Envelope {
    "@attack":  string;
    "@decay":   string;
    "@sustain": string;
    "@release": string;
}

export interface Equalizer {
    "@bass":            string;
    "@treble":          string;
    "@bassFrequency":   string;
    "@trebleFrequency": string;
}

export interface PatchCable {
    "@source":      string;
    "@destination": string;
    "@amount":      string;
}

export interface Delay {
    "@pingPong":  string;
    "@analog":    string;
    "@syncLevel": string;
}

export interface Lfo1 {
    "@syncLevel": string;
}

export interface ModKnob {
    "@controlsParam":          string;
    "@patchAmountFromSource"?: string;
}

export interface Modulator1 {
    "@transpose":     string;
    "@cents":         string;
    "@retrigPhase":   string;
    "@toModulator1"?: string;
}

export interface Unison {
    "@num":    string;
    "@detune": string;
}
