// Generated by https://quicktype.io

export interface SynthSamples {
    "@firmwareVersion":            string;
    "@earliestCompatibleFirmware": string;
    "@polyphonic":                 string;
    "@voicePriority":              string;
    "@mode":                       string;
    "@lpfMode":                    string;
    "@modFXType":                  string;
    osc1:                          Osc1;
    osc2:                          Osc2;
    lfo1:                          Lfo1;
    lfo2:                          any[];
    unison:                        Unison;
    compressor:                    Compressor;
    delay:                         Delay;
    defaultParams:                 DefaultParams;
    arpeggiator:                   Arpeggiator;
    modKnobs:                      ModKnob[];
}

export interface Arpeggiator {
    "@mode":       string;
    "@numOctaves": string;
    "@syncLevel":  string;
}

export interface Compressor {
    "@syncLevel": string;
    "@attack":    string;
    "@release":   string;
}

export interface DefaultParams {
    "@arpeggiatorGate":     string;
    "@portamento":          string;
    "@compressorShape":     string;
    "@oscAVolume":          string;
    "@oscAPulseWidth":      string;
    "@oscBVolume":          string;
    "@oscBPulseWidth":      string;
    "@noiseVolume":         string;
    "@volume":              string;
    "@pan":                 string;
    "@lpfFrequency":        string;
    "@lpfResonance":        string;
    "@hpfFrequency":        string;
    "@hpfResonance":        string;
    "@lfo1Rate":            string;
    "@lfo2Rate":            string;
    "@modulator1Amount":    string;
    "@modulator1Feedback":  string;
    "@modulator2Amount":    string;
    "@modulator2Feedback":  string;
    "@carrier1Feedback":    string;
    "@carrier2Feedback":    string;
    "@modFXRate":           string;
    "@modFXDepth":          string;
    "@delayRate":           string;
    "@delayFeedback":       string;
    "@reverbAmount":        string;
    "@arpeggiatorRate":     string;
    "@stutterRate":         string;
    "@sampleRateReduction": string;
    "@bitCrush":            string;
    "@modFXOffset":         string;
    "@modFXFeedback":       string;
    envelope1:              Envelope;
    envelope2:              Envelope;
    patchCables:            PatchCables;
    equalizer:              Equalizer;
}

export interface Envelope {
    "@attack":  string;
    "@decay":   string;
    "@sustain": string;
    "@release": string;
}

export interface Equalizer {
    "@bass":            string;
    "@treble":          string;
    "@bassFrequency":   string;
    "@trebleFrequency": string;
}

export interface PatchCables {
    patchCable: PatchCable;
}

export interface PatchCable {
    "@source":      string;
    "@destination": string;
    "@amount":      string;
}

export interface Delay {
    "@pingPong":  string;
    "@analog":    string;
    "@syncLevel": string;
}

export interface Lfo1 {
    "@syncLevel": string;
}

export interface ModKnob {
    "@controlsParam":          string;
    "@patchAmountFromSource"?: string;
}

export interface Osc1 {
    "@loopMode":          string;
    "@reversed":          string;
    "@timeStretchEnable": string;
    "@timeStretchAmount": string;
    sampleRanges?:         SampleRange[];
}

export interface SampleRange {
    "@rangeTopNote"?: string;
    "@fileName":      string;
    "@transpose"?:    string;
    "@cents"?:        string;
    zone:             Zone;
}

export interface Zone {
    "@startSamplePos": string;
    "@endSamplePos":   string;
    "@startLoopPos":   string;
    "@endLoopPos"?:    string;
}

export interface Osc2 {
    "@transpose":   string;
    "@cents":       string;
    "@retrigPhase": string;
    sampleRanges?:  SampleRange[];
}

export interface Unison {
    "@num":    string;
    "@detune": string;
}
